---
title: "Project Two"
author: "Wendy Du Bois"
date: "5/29/2021"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load data}
#load the mlbench package which has the BreastCancer data set
#install.packages("mlbench")
require(mlbench)
# if you don't have any required package, use the install.packages() command
# load the data set
data(BreastCancer)
# some algorithms don't like missing values, so remove rows with missing values
BreastCancer <- na.omit(BreastCancer) 
# remove the unique identifier, which is useless and would confuse the machine learning algorithms
BreastCancer$Id <- NULL
mydata <- BreastCancer
df <-BreastCancer

```


SVM Prediction
```{r SVM}
library(e1071)
mysvm <- svm(Class ~ ., BreastCancer)
mysvm.pred <- predict(mysvm, BreastCancer)
table(mysvm.pred,BreastCancer$Class)

mysvm
mysvm.pred

```

NaiveBayes Prediction
```{r NaiveBayes}
#install.packages("klaR")

library(klaR)
mynb <- NaiveBayes(Class ~ ., BreastCancer)
mynb.pred <- predict(mynb,BreastCancer)
table(mynb.pred$class,BreastCancer$Class)

```

Neural Net Prediction
```{r nnet}
library(nnet)
mynnet <- nnet(Class ~ ., BreastCancer, size=1)
mynnet.pred <- predict(mynnet,BreastCancer,type="class")
table(mynnet.pred,BreastCancer$Class)

```


Decision tree Prediction
```{r Decision trees}
#Decision trees
library(MASS)
library(rpart)
mytree <- rpart(Class ~ ., BreastCancer)
plot(mytree); text(mytree) # in "BreastCancer_tree.ps"
summary(mytree)
mytree.pred <- predict(mytree,BreastCancer,type="class")
table(mytree.pred,BreastCancer$Class)

```

Leave-1-Out Cross Validation (LOOCV) Prediction
```{r Leave-1-Out Cross Validation (LOOCV)}
# Leave-1-Out Cross Validation (LOOCV)
ans <- numeric(length(BreastCancer[,1]))
for (i in 1:length(BreastCancer[,1])) {
  mytree <- rpart(Class ~ ., BreastCancer[-i,])
  mytree.pred <- predict(mytree,BreastCancer[i,],type="class")
  ans[i] <- mytree.pred
}
ans <- factor(ans,labels=levels(BreastCancer$Class))
table(ans,BreastCancer$Class)
# The same as above in this case
```

Quadratic Discriminant Analysis Prediction
```{r Quadratic Discriminant Analysis with Brians code}
df2<-df
#convert to integers #There are better ways to do this conversion
df2$Cl.thickness<-as.integer(df$Cl.thickness)
df2$Class<-ifelse(as.integer(df$Class)==2,1,0) #I had Class converted to a dummy variable
df2$Mitoses<-as.integer(df$Mitoses)
df2$Cell.size<-as.integer(df$Cell.size)
df2$Cell.shape<-as.integer(df$Cell.shape)
df2$Marg.adhesion<-as.integer(df$Marg.adhesion)
df2$Epith.c.size<-as.integer(df$Epith.c.size)
df2$Bare.nuclei<-as.integer(df$Bare.nuclei)
df2$Bl.cromatin<-as.integer(df$Bl.cromatin)
df2$Normal.nucleoli<-as.integer(df$Normal.nucleoli)

myqda <- qda(Class ~ ., data=df2)
myqda.pred <- predict(myqda, df2)
table(myqda.pred$class,df2$Class)

```


Regularised Discriminant Analysis (RDA) Prediction
```{r Regularised Discriminant Analysis}
#Regularised Discriminant Analysis
library(klaR)
myrda <- rda(Class ~ ., BreastCancer)
myrda.pred <- predict(myrda, BreastCancer)
table(myrda.pred$class,BreastCancer$Class)

```

Random Forests Prediction
```{r Random Forests}
#Random Forests
library(randomForest)
myrf <- randomForest(Class ~ .,BreastCancer)
myrf.pred <- predict(myrf, BreastCancer)
table(myrf.pred, BreastCancer$Class)

```

Combination of Classifiers Prediction
```{r}
combine.classes<-data.frame(myrf.pred, myrda.pred$class,mytree.pred,mynnet.pred,mysvm.pred,mynb.pred$class)
combine.classes$myrf.pred<-ifelse(combine.classes$myrf.pred=="benign", 0, 1)
combine.classes[,2]<-ifelse(combine.classes[,2]=="benign", 0, 1)
combine.classes[,3]<-ifelse(combine.classes[,3]=="benign", 0, 1)
combine.classes[,4]<-ifelse(combine.classes[,4]=="benign", 0, 1)
combine.classes[,5]<-ifelse(combine.classes[,5]=="benign", 0, 1)
combine.classes[,6]<-ifelse(combine.classes[,6]=="benign", 0, 1)
majority.vote=rowSums(combine.classes)
combine.classes[,7]<-rowSums(combine.classes)
combine.classes[,8]<-ifelse(combine.classes[,7]>=4, "malignant", "benign")
table(combine.classes[,8], BreastCancer$Class)
```



